[package]
name = "tlsimple"
description = "Some kkocdko's crazy ideas about TLS & HTTPS supports in async Rust."
version = "0.1.0"
edition = "2021"
license = "MIT"

[dependencies]
# tokio = { version = "1", features = ["rt-multi-thread", "macros", "time", "fs"] }
