[package]
name = "tlsimple"
description = "Simple and tiny TLS supports for Rust (Async FFI of Mbed TLS)."
version = "0.1.2"
edition = "2021"
license = "MIT"

[dependencies]
tokio = { version = "1", features = ["rt-multi-thread", "macros", "time", "fs", "net", "io-util"] }

[build-dependencies]
cc = { version = "1", features = ["parallel"] }
