name: ci
on: [push, pull_request]
jobs:
  ci:
    strategy: { matrix: { os: [windows-2022, ubuntu-22.04, macos-13] } }
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    steps:
      - name: Git checkout
        uses: actions/checkout@v3
      - name: Show Rust toolchain versions
        run: rustup show
      - name: Cargo test
        run: cargo test --example demo
