name: ci
on: [push, pull_request]
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Git Clone
        run: git clone --depth=1 $GITHUB_SERVER_URL/$GITHUB_REPOSITORY .
      - name: Cargo Test
        run: rustup show ; sh ./project.sh init ; sh ./project.sh run-rust test
